### ISSUE TITLE
[Làm giá] Cách thức theo dõi xin bảng giá, cập nhật bảng giá 

### ISSUE THREAD

**Issue by phatls** [phatls/20160426_KiemSoatNoiBo#7]

**Comment by TrongDV** [comment]
Có 2 cách xin bảng giá:
1. Dựa vào người làm việc trực tiếp với NCC( người khai phá NCC) hoặc người đang phụ trách phần này có nhiệm vụ xin bảng giá từ NCC.
2. Dựa vào người mua hàng. Sáng thứ 2 hàng tuần nhờ người mua hàng xác nhận với NCC xem giá có thay đổi gì không và khi nào có biến thì thông báo lại để bộ phận làm giá biết cập nhật kịp thời.
